image: python:3.7
before_script:
  - python -V
  - pip install virtualenv

stages:
  - build
  - execute

Installing Requirements:
  stage: build
  script:
    - python -m virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    expire_in: 10 minutes

Running the Script:
  stage: execute
  script:
    - source venv/bin/activate
    - python hello-world-requirements.py
